config/routes.rb
RailsTest::Application.routes.draw do
  resources :first_names

end

app/models/first_name.rb
class FirstName < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/first_names_controller.rb
class FirstNamesController < ApplicationController
  before_action :set_first_name, only: [:show, :edit, :update, :destroy]

  # GET /first_names
  # GET /first_names.json
  def index
    @first_names = FirstName.all
  end

  # GET /first_names/1
  # GET /first_names/1.json
  def show
  end

  # GET /first_names/new
  def new
    @first_name = FirstName.new
  end

  # GET /first_names/1/edit
  def edit
  end

  # POST /first_names
  # POST /first_names.json
  def create
    @first_name = FirstName.new(first_name_params)

    respond_to do |format|
      if @first_name.save
        format.html { redirect_to @first_name, notice: 'First name was successfully created.' }
        format.json { render action: 'show', status: :created, location: @first_name }
      else
        format.html { render action: 'new' }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_names/1
  # PATCH/PUT /first_names/1.json
  def update
    respond_to do |format|
      if @first_name.update(first_name_params)
        format.html { redirect_to @first_name, notice: 'First name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_names/1
  # DELETE /first_names/1.json
  def destroy
    @first_name.destroy
    respond_to do |format|
      format.html { redirect_to first_names_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_name
      @first_name = FirstName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_name_params
      params.require(:first_name).permit(:lastName, :birthday, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_names_helper.rb
module FirstNamesHelper
end

app/views/first_names/_form.html.erb
<%= form_for(@first_name) do |f| %>
  <% if @first_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first_name.errors.count, "error") %> prohibited this first_name from being saved:</h2>

      <ul>
      <% @first_name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.number_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/first_names/edit.html.erb
<h1>Editing first_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @first_name %> |
<%= link_to 'Back', first_names_path %>

app/views/first_names/index.html.erb
<h1>Listing first_names</h1>

<table>
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Birthday</th>
      <th>Website</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @first_names.each do |first_name| %>
      <tr>
        <td><%= first_name.lastName %></td>
        <td><%= first_name.birthday %></td>
        <td><%= first_name.website %></td>
        <td><%= link_to 'Show', first_name %></td>
        <td><%= link_to 'Edit', edit_first_name_path(first_name) %></td>
        <td><%= link_to 'Destroy', first_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New First name', new_first_name_path %>

app/views/first_names/new.html.erb
<h1>New first_name</h1>

<%= render 'form' %>

<%= link_to 'Back', first_names_path %>

app/views/first_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @first_name.lastName %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @first_name.birthday %>
</p>

<p>
  <strong>Website:</strong>
  <%= @first_name.website %>
</p>

<%= link_to 'Edit', edit_first_name_path(@first_name) %> |
<%= link_to 'Back', first_names_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>